export const configSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  title: 'CC-Ding Client Config',
  type: 'object',
  properties: {
    clientName: { type: 'string', description: '客户端显示名称' },
    owner: { type: 'string', description: 'Owner 手机号或工号' },
    model: { type: 'string', description: '默认模型' },
    clientSecret: { type: 'string', description: '钉钉 Stream Client 密钥' },
    defaultDingToken: { type: 'string', description: '兜底钉钉机器人 Token' },
    whiteUserList: { type: 'array', items: { type: 'string' }, description: '白名单用户列表' },
    adminUserList: { type: 'array', items: { type: 'string' }, description: '管理员列表' },
    ownerConversationId: { type: 'string', description: 'Owner 单聊会话 ID' },
    preBash: { type: 'string', description: '前置命令' },
    dingSecret: { type: 'string', description: '钉钉签名密钥' },
    debug: { type: 'boolean', description: 'DEBUG 模式' },
    resultOnly: { type: 'boolean', description: '结果模式' },
    includeThinking: { type: 'boolean', description: '包含思考过程' },
    enableMsgToUser: { type: 'boolean', description: '启用单聊消息' },
    taskQueueSize: { type: 'integer', minimum: 1, description: '任务队列大小' },
    sessionMaxConcurrency: { type: 'integer', minimum: 1, description: '最大并发会话数' },
    maxTurnTimeMins: { type: 'integer', minimum: 0, description: 'Watchdog 超时时间（分钟）' },
    maxAutoRecovery: { type: 'integer', minimum: 0, description: '自动恢复次数' },
    cardTemplateId: { type: 'string', description: 'AI Card 模板 ID' },
    cardTemplateKey: { type: 'string', description: 'AI Card 模板变量名' },
    taskHandlerCount: { type: 'integer', minimum: 1, description: '任务处理器数量' },
    recorderCfg: {
      type: 'object',
      description: 'Recorder 模式配置',
      properties: {
        dist: { type: 'string', description: '保存目录' },
      },
    },
    retryCfg: {
      type: 'object',
      description: '无限重试检测配置',
      properties: {
        maxDurationSecs: { type: 'integer', minimum: 60, description: '最大重试持续时间（秒）' },
        maxCount: { type: 'integer', minimum: 1, description: '最大重试次数' },
        minCountForDuration: { type: 'integer', minimum: 1, description: '持续时间触发最小重试次数' },
        retryCooldownSecs: { type: 'integer', minimum: 30, description: 'retryLogs 命中后 API Key 冷却时长（秒）' },
      },
    },
    envs: {
      type: 'object',
      description: '自定义环境变量',
      additionalProperties: { type: 'string' },
    },
    conversations: {
      type: 'array',
      description: '会话列表',
      items: {
        type: 'object',
        properties: {
          conversationId: { type: 'string', description: '会话 ID' },
          conversationTitle: { type: 'string', description: '会话标题' },
          conversationType: { type: 'string', enum: ['1', '2'], description: '1=单聊，2=群聊' },
          dingToken: { type: 'string' },
          whiteUserList: { type: 'array', items: { type: 'string' } },
          linkConversationId: { type: 'string', description: '关联的主会话 ID' },
          model: { type: 'string' },
          agent: { type: 'string' },
          streaming: { type: 'boolean' },
          qaMode: { type: 'boolean' },
          freedomMode: { type: 'boolean' },
          permissionMode: { type: 'string', enum: ['acceptEdits', 'bypassPermissions', 'plan', 'auto', 'dontAsk'] },
          preBash: { type: 'string' },
          workDir: { type: 'string' },
          receiveReply: { type: 'boolean' },
          receiveReplyMode: { type: 'string', enum: ['reaction', 'text'] },
          ackReaction: { type: 'string' },
          atSender: { type: 'boolean' },
          ensureAt: { type: 'boolean' },
          useLocalOcr: { type: 'boolean' },
          maxTurnTimeMins: { type: 'integer' },
          mobile: { type: 'string', description: '单聊目标用户手机号' },
          qaCfg: {
            type: 'object',
            description: 'QA 模式配置',
            properties: {
              gitRepos: { type: 'array', items: { type: 'string' }, description: 'Git 仓库列表' },
              docs: { type: 'array', items: { type: 'string' }, description: '文档 URL 列表' },
              autoPull: { type: 'boolean', description: '自动 Pull' },
            },
          },
          envs: {
            type: 'object',
            description: '会话级自定义环境变量',
            additionalProperties: { type: 'string' },
          },
        },
        required: ['conversationId', 'conversationType'],
      },
    },
    a2aCfg: {
      type: 'object',
      description: 'A2A 配置',
      properties: {
        hubUrl: { type: 'string' },
        apiKey: { type: 'string' },
        remoteAgents: { type: 'array' },
      },
    },
  },
}
